### PR TITLE
Fixes for F* change, use compat options

### PR DESCRIPTION
**Pull request by mtzguido**
## Proposed changes

The F* PR https://github.com/FStarLang/FStar/pull/3072 is fixing a pretty old bug in which values memoized during normalization can "leak" across configurations or different norm requests (https://github.com/FStarLang/FStar/issues/2155). The PR fixes the problem, but a handful of proofs in HACL* regress. This PR fixes the breakage by the use of a compatibility option.

Most of the failures come from Vale code, which uses custom normalization calls heavily. There's another failure in a big proof that also uses a lot of normalization.

I did not get to the bottom of why this changes/fails, and instead I am just setting a compatibility option. As far as I can see this code is not frequently edited.. so the compatibility options may be fine, but wondering what you folks think...

I'll update this PR with an everest green soon, running over the new F*. I think this will come back green so we can merge it before the F* PR to avoid the downtime.

Thanks!

## Types of changes

What types of changes does your code introduce to HACL*?
_Put an `x` in the boxes that apply_

- [x] Proof maintenance (non-breaking change which fixes a proof regression)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New algorithm or feature (non-breaking change which adds functionality)
- [ ] Improved performance (fix or feature that would improve performance of some algorithm on some platform)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CODE_OF_CONDUCT.md](https://github.com/hacl-star/hacl-star/blob/main/CODE_OF_CONDUCT.md) doc
- [x] I have read and agree to submit my changes under the [LICENSE](https://github.com/hacl-star/hacl-star/blob/main/LICENSE)
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have edited [CHANGES.md](https://github.com/hacl-star/hacl-star/blob/main/CHANGES.md) (if appropriate)

### CODE REVIEW

**Comment by msprotz** [comment]
Pinging @Chris-Hawblitzel for the Vale changes, and @polubelova and @karthikbhargavan for the ed25519 changes. Thanks for the PR!

**Comment by mtzguido** [comment]
Thanks! Here's the everest green: https://github.com/project-everest/everest/actions/runs/6673142923.

I'm now noticing I added the hints in this PR... not sure that's needed/desirable. Feel free to not take that commit (or I can remove it too)

**Review by polubelova — APPROVED** [review]
Looks good to me, thank you! 

Pinging @R1kM, since he proved this lemma for Ed25519.

**Comment by mtzguido** [comment]
Thanks! FWIW I think the Ed25519 proof is just a random failure, it failed locally for me again with another unrelated F* change

**Comment by mtzguido** [comment]
OK, just updated this PR with some proof taming for the Ed25519 file, the compat flag is not needed.

The changes in Vale files are the same as before, just setting the compat option.

**Comment by mtzguido** [comment]
Just FYI I'm merging https://github.com/FStarLang/FStar/pull/3074 (a different PR!) to F*, which does not add any functional change, but iirc it did make this Ed25519 proof regress locally. The first commit in this PR should fix it, if it does break.

I'll wait on the compat stuff for a bit in case there are objections.

**Comment by Chris-Hawblitzel** [comment]
The Vale changes look good to me.

**Review by msprotz — APPROVED** [review]

**Comment by msprotz** [comment]
let's unblock this... thanks Guido!

**Comment by msprotz** [comment]
```
 hacl-star> Failed after: 0:59.35
hacl-star> Full log is in obj/Vale.Poly1305.CallingFromLowStar.fst.checked.{out,err}, see excerpt below:
hacl-star> * Error 19 at /build/source/vale/code/crypto/poly1305/x64/Vale.Poly1305.CallingFromLowStar.fst(199,4-199,114):
hacl-star>   - Subtyping check failed; expected type Vale.X64.Machine_s.nat128; got type Prims.int
hacl-star>   - The SMT solver could not prove the query. Use --query_stats for more details.
hacl-star>   - See also prims.fst(659,18-659,24)
hacl-star> Verified module: Vale.Poly1305.CallingFromLowStar
hacl-star> 1 error was reported (see above)
```

**Comment by mtzguido** [comment]
Surprised by that, sorry, running another build now with an up-to-date F*.

**Comment by mtzguido** [comment]
Seems like just a bit of flakiness. Using --retry 2 worked, and updated the hints, and now it works fine. I added the new hints for that file to the PR. An alternative

**Comment by msprotz** [comment]
That's fine enough for now, thanks

**Pull request merged**
