### PR TITLE
Vale.{X64,PPC64LE}.QuickCodes: erasing ranges

### PR DESCRIPTION
**Pull request by mtzguido**
Ranges are for tagging terms for error reporting, and the fact that they extract (for normal OCaml applications) is arguably shady: their implementation is the internal `FStarC.Compiler.Range.Type.range`, which is included in fstar.lib like the rest of the compiler. This will be gone soon with a new build and leaner fstar.lib, and this would fail.

Regardless of that, it's anyway cleaner to erase these to make the generated OCaml simpler.

I'm not sure what place this has in the rest of the build, but maybe more things here can be erased (the `quickCodes` type?).

There's also no need to merge this yet if there are doubts, I'm working on forks of F*/krml/hacl and can post a PR when they all work together well, with this patch in it.

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to HACL*?
_Put an `x` in the boxes that apply_

*Not exactly sure how to tag this*

- [ ] Proof maintenance (non-breaking change which fixes a proof regression)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New algorithm or feature (non-breaking change which adds functionality)
- [ ] Improved performance (fix or feature that would improve performance of some algorithm on some platform)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CODE_OF_CONDUCT.md](https://github.com/hacl-star/hacl-star/blob/main/CODE_OF_CONDUCT.md) doc
- [x] I have read and agree to submit my changes under the [LICENSE](https://github.com/hacl-star/hacl-star/blob/main/LICENSE)
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have edited [CHANGES.md](https://github.com/hacl-star/hacl-star/blob/main/CHANGES.md) (if appropriate)

### CODE REVIEW

**Comment by R1kM** [comment]
I can't remember precisely how they were used, @Chris-Hawblitzel is the expert here.

Quickcodes are the custom VC generation for Vale, where the parts of the VCs operating on registers are heavily simplified by normalization, removing some heavy parts of the wp-calculus encoding (described in the POPL 19 paper). If I remember correctly, the msg associated to the different nodes allows precise error reporting w.r.t. the original Vale code, however, I believe the Vale ranges are directly included in the msg, so I am uncertain about the use of the range (apart from being needed to create a labeled value to pass to the SMT).

As long as this behavior can be preserved and Chris confirms that ranges are not needed in another way, I'm happy to merge this

**Comment by Chris-Hawblitzel** [comment]
Yes, erasing the labels makes sense to me.  They are only used, via `Prims.labeled`, to help F* build a more informative SMT query with more useful error messages about the line numbers in the original Vale source program that is being verified.

Yes, probably the whole `quickCodes` type could be erased.

**Comment by mtzguido** [comment]
Thanks! I'll try erasing a bit more and will confirm if the error reporting still works (it really should).

**Comment by mtzguido** [comment]
Updated erasing more, also using new attribute syntax. The error reporting seems to still work, this diff (I randomly changed one line):
```diff
--- a/vale/code/crypto/aes/x64/Vale.AES.X64.GCTR.vaf
+++ b/vale/code/crypto/aes/x64/Vale.AES.X64.GCTR.vaf
@@ -574,7 +574,7 @@ procedure Gctr_bytes(
         cipher_bytes == gctr_encrypt_LE(old(icb), make_gctr_plain_LE(plain_bytes), alg, key);
 {
     Mov64(tmp, num_blocks);
-    IMul64(tmp, 16);    // # of bytes in even 128-bit blocks
+    IMul64(tmp, 160);    // # of bytes in even 128-bit blocks
     Gctr_core_opt(alg, in_b, out_b, key, round_keys, keys_b);
     assert gctr_partial_def(alg, old(num_blocks), s128(heap0, in_b), s128(heap1, out_b), key, old(icb));
     assert icb == inc32(old(icb), old(num_blocks));
```
gives:
```
* Error 19 at /home/guido/r/hacl-star/dev/obj/Vale.AES.X64.GCTR.fst(1501,35-1501,52):
  - ***** PRECONDITION NOT MET AT line 591 column 22 of file /home/guido/r/hacl-star/dev/vale/code/crypto/aes/x64/Vale.AES.X64.GCTR.vaf *****
  - The SMT solver could not prove the query. Use --query_stats for more
    details.
  - See also /home/guido/r/hacl-star/dev/vale/code/crypto/aes/Vale.AES.GCTR.fsti(205,27-205,29)

* Error 19 at /home/guido/r/hacl-star/dev/obj/Vale.AES.X64.GCTR.fst(1589,18-1589,20):
  - ***** POSTCONDITION NOT MET AT line 574 column 93 of file /home/guido/r/hacl-star/dev/vale/code/crypto/aes/x64/Vale.AES.X64.GCTR.vaf *****
  - The SMT solver could not prove the query. Use --query_stats for more
    details.
```

**Review by R1kM — APPROVED** [review]
Thanks Guido!

**Pull request merged**
