### PR TITLE
Nix: enable resource monitoring

### LINKED ISSUE #761: Run resource monitoring on CI
The resource monitoring introduced in #727 should be run on CI to ensure proof performance does not regress.

### PR DESCRIPTION
**Pull request by pnmadelaine**
## Proposed changes

Enable resource monitoring in Nix and add a Hydra job that outputs the result of the monitoring.
Fixes #761.

## Types of changes

- [ ] Proof maintenance (non-breaking change which fixes a proof regression)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New algorithm or feature (non-breaking change which adds functionality)
- [ ] Improved performance (fix or feature that would improve performance of some algorithm on some platform)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CODE_OF_CONDUCT.md](https://github.com/hacl-star/hacl-star/blob/main/CODE_OF_CONDUCT.md) doc
- [x] I have read and agree to submit my changes under the [LICENSE](https://github.com/hacl-star/hacl-star/blob/main/LICENSE)
- [x] I have added necessary documentation (if appropriate)
- [x] I have edited [CHANGES.md](https://github.com/hacl-star/hacl-star/blob/main/CHANGES.md) (if appropriate)

### CODE REVIEW

**Review by R1kM — APPROVED** [review]
Looks good to me, thanks. How do you retrieve the output of runlim after CI success?

**Review by franziskuskiefer — APPROVED** [review]
Thanks.

> @R1kM on Hydra there is now a job called "hacl-resource-monitor" which shows a text file named "resources.txt", it contains the output of https://github.com/FStarLang/FStar/blob/master/.scripts/res_summary.sh

Similar to what I said on slack about the ci bot messages. Let's describe how this works and what it is in some markdown file in the repo here so we can link to it and everyone can read up on how to get and interpret the CI results.

**Comment by msprotz** [comment]
That's great! Any chance we could make this more visible, either through a slack notification or a github comment on the pull request?

**Comment by pnmadelaine** [comment]
> That's great! Any chance we could make this more visible, either through a slack notification or a github comment on the pull request?

I can also add a github status from the Hydra job. The job should never fail if the main Hydra job didn't fail.

**Pull request merged**
