### PR TITLE
Improve the treatment of Lib.Memzero following the latest changes in krml

### PR DESCRIPTION
**Pull request by msprotz**
See https://github.com/FStarLang/karamel/pull/364 for rationale

### CODE REVIEW

**Comment by msprotz** [comment]
does anyone know why the build has not started? @pnmadelaine

**Review by R1kM — APPROVED** [review]

**Review by karthikbhargavan — APPROVED** [review]

**Comment by franziskuskiefer** [comment]
@msprotz this breaks hacl-packages because the header has a different name than the corresponding C file.
We have to rename one of them.

**Comment by msprotz** [comment]
so Lib_Memzero0.h is gone, replaced by lib_memzero0.h and Lib_Memzero0.c remains (notice the case).

What would you like to see?

**Comment by msprotz** [comment]
yeah the casing encodes whether it's a hand-written file or an auto-generated one

no issues with renaming libmemzero0.h to lib_memzero0.h, would that help?

**Comment by franziskuskiefer** [comment]
> no issues with renaming libmemzero0.h to lib_memzero0.h, would that help?

I can try to update the build script to see if that works. But it's not ideal ...

**Pull request merged**
