### PR TITLE
Meta.Interface: update for new F*

### PR DESCRIPTION
**Pull request by mtzguido**
This is _going to_ be needed once F* merges https://github.com/FStarLang/FStar/pull/2835 (which is ready). It's just adjusting to changes in the type of `binder_view` and the introduction of sealed names in reflection.

I don't really see a way to stage it... so I think we should merge simultaneously. I'll update this with a pointer to a green everest build soon (fixing everparse now).

EDIT: green here https://github.com/project-everest/everest/commit/2a260cde0fbd82ee4385f1fa6f14361b7e47fe3d

---------------

The type `binder_view` is now a record, and its ppnames are sealed.

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to HACL*?
_Put an `x` in the boxes that apply_

- [X] Proof maintenance (non-breaking change which fixes a proof regression)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New algorithm or feature (non-breaking change which adds functionality)
- [ ] Improved performance (fix or feature that would improve performance of some algorithm on some platform)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the [CODE_OF_CONDUCT.md](https://github.com/hacl-star/hacl-star/blob/main/CODE_OF_CONDUCT.md) doc
- [X] I have read and agree to submit my changes under the [LICENSE](https://github.com/hacl-star/hacl-star/blob/main/LICENSE)
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have edited [CHANGES.md](https://github.com/hacl-star/hacl-star/blob/main/CHANGES.md) (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by R1kM — APPROVED** [review]
Thanks!

**Review by polubelova — APPROVED** [review]
Thanks!

**Comment by mtzguido** [comment]
Everparse is now good, so we could merge the F* PR + this one. How can we do that? Both at once, overriding the protection? Or merge the F* PR (causing breakage) and re-kick a build here?

(Note: F* slightly changed since the everest green I posted above, but the changes are only build-related, so it would be very surprising that something fails. But I could run another build if desired.)

**Comment by polubelova** [comment]
Let's merge both at once, no need to wait for a new build

**Comment by mtzguido** [comment]
Sounds good, thanks! Should I merge the F* one and wait for a HACL maintainer to merge this one then? (I believe I don't have permissions)

**Comment by polubelova** [comment]
Yep, I'll merge this one. Thanks!

**Pull request merged**
