### PR TITLE
Include `alloca.h` in `Hacl_Bignum_Base.h` for mozilla dist

### LINKED ISSUE #868: Missing alloca.h include for dist/mozilla
This is a followup to #857.
Compilation fails on some systems when the `alloca.h` include is missing.
We can either add it during extraction, or modify `builtin.h` to include it. I'd vote to add it to the extraction to get a quick fix and then consider adding it to the `builtin.h`.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1857190 for the original bug report.

I don't know how to reproduce but it's on Solaris

### PR DESCRIPTION
**Pull request by franziskuskiefer**
I didn't test it, but something like this should fix the issue.

Fixes #868

### CODE REVIEW

**Comment by msprotz** [comment]
What is the issue? On which build platforms? 

We have this: https://github.com/FStarLang/karamel/blob/master/include/krml/internal/builtin.h which is perhaps what needs to be replicated?

**Comment by franziskuskiefer** [comment]
> What is the issue? On which build platforms?

See the linked issue #868.

**Comment by msprotz** [comment]
let me try to upstream the fix it should take just as long as this PR -- see fstarlang/karamel#386

**Comment by msprotz** [comment]
(The reason I want to do it this way is that alloca.h is not available on windows, so this would likely break your windows build.

**Comment by franziskuskiefer** [comment]
👍🏻 sure, fixing it properly right away is better.

**Comment by msprotz** [comment]
Fixed via #870

**Pull request closed without merging**
