### PR TITLE
Improve and beat previous perf on the sha2 streaming work by bundling everything together

### PR DESCRIPTION
**Pull request by msprotz**
Some long-standing changes on top of #756.
- Ditch SHA2-MB-specific reasoning in Hacl.Streaming.MD (YAY!!) -- this was a stopgap until we could finally get our stuff together. Now that Hacl.Hash.SHA2 is a tight abstraction that i) calls SHA2/MB under the hood and ii) exposes exactly the right signatures, we can go back to the previous state of affairs where the MD generic instance of the streaming functor only goes through the Hacl.Hash.* modules.
- Bundle all the SHA2 stuff together in a single C file. This is what yields the performance gain, I think.
- Move one-shot functions to the Hacl.Streaming.SHA2.fst to avoid dependency loops. This requires a patch on hacl-packages which I am providing free of charge below. Thanks.

[hacl-packages.patch](https://github.com/hacl-star/hacl-star/files/11503765/hacl-packages.patch)

### CODE REVIEW

**Comment by msprotz** [comment]
@R1kM @karthikbhargavan @polubelova: I have isolated this change as a separate PR to make this easy to review. My hope is that you can review this in isolation (to see the effect on the C code), then we merge this into #756 and merge #756 as soon as it's green.

**Review by karthikbhargavan — COMMENTED** [review]
This is a more general comment about naming, but it is a bit weird that all the functions in Hacl_Hash_SHA2.c are named Hacl_Streaming_***. Is there some way we could rename these to Hacl_Hash_* in the bundling file, leaving Hacl_Streaming_* only for the internal functions?

**Comment by msprotz** [comment]
Yeah there's rename-prefix in the krml bundle language that mostly does that. @pnmadelaine's PR starts introducing rename-prefix aggressively to align all of these names -- I've refrained from doing so here because I want to keep the changes minimal, but it's of course possible to turn on that option

**Comment by karthik-cryspen** [comment]
Some numbers from a Macbook Pro M1.

Before this patch, numbers from `karthik/sha2_benchmark` on hacl-packages were:
```
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
HACL_Sha2_oneshot/sha2_224              3130 ns         3130 ns       223390
EverCrypt_Sha2_oneshot/sha2_224         6588 ns         6587 ns       105932
OpenSSL_hash_oneshot/sha2_224            547 ns          541 ns      1290418
HACL_Sha2_oneshot/sha2_256              3135 ns         3134 ns       220119
EverCrypt_Sha2_oneshot/sha2_256         6568 ns         6567 ns       105296
OpenSSL_hash_oneshot/sha2_256            540 ns          539 ns      1290370
HACL_Sha2_oneshot/sha2_384              1990 ns         1989 ns       353369
EverCrypt_Sha2_oneshot/sha2_384         3288 ns         3287 ns       213218
OpenSSL_hash_oneshot/sha2_384            838 ns          838 ns       833780
HACL_Sha2_oneshot/sha2_512              1980 ns         1980 ns       350992
EverCrypt_Sha2_oneshot/sha2_512         3295 ns         3287 ns       214193
OpenSSL_hash_oneshot/sha2_512            841 ns          839 ns       832333
HACL_Sha2_streaming/sha2_224            3807 ns         3798 ns       185217
EverCrypt_Sha2_streaming/sha2_224       7453 ns         7450 ns        94020
OpenSSL_hash_streaming/sha2_224         1649 ns         1648 ns       425431
HACL_Sha2_streaming/sha2_256            3802 ns         3797 ns       185922
EverCrypt_Sha2_streaming/sha2_256       7476 ns         7471 ns        93633
Digestif_sha256                         5678 ns         5676 ns       122586
OpenSSL_hash_streaming/sha2_256         1638 ns         1630 ns       429232
HACL_Sha2_streaming/sha2_384            2630 ns         2630 ns       265512
EverCrypt_Sha2_streaming/sha2_384       4126 ns         4125 ns       169728
OpenSSL_hash_streaming/sha2_384         1890 ns         1889 ns       367985
HACL_Sha2_streaming/sha2_512            2630 ns         2629 ns       264484
EverCrypt_Sha2_streaming/sha2_512       4147 ns         4146 ns       168690
Digestif_sha512                         3899 ns         3898 ns       180352
OpenSSL_hash_streaming/sha2_512         1892 ns         1891 ns       369905
```

Here `HACL_*` are calling into SHA2-MB, whereas `EverCrypt_*` are calling into the old streaming SHA2. 

After this patch, the numebers from `hacl-star-protz_sha2_thin_wrapper` on `hacl-packages` are:
```
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
HACL_Sha2_oneshot/sha2_224              3132 ns         3131 ns       223789
EverCrypt_Sha2_oneshot/sha2_224         3144 ns         3141 ns       223806
OpenSSL_hash_oneshot/sha2_224            549 ns          549 ns      1263834
HACL_Sha2_oneshot/sha2_256              3129 ns         3129 ns       223039
EverCrypt_Sha2_oneshot/sha2_256         3129 ns         3128 ns       222366
OpenSSL_hash_oneshot/sha2_256            552 ns          552 ns      1265319
HACL_Sha2_oneshot/sha2_384              1987 ns         1986 ns       352517
EverCrypt_Sha2_oneshot/sha2_384         1990 ns         1989 ns       352423
OpenSSL_hash_oneshot/sha2_384            845 ns          845 ns       826778
HACL_Sha2_oneshot/sha2_512              1988 ns         1987 ns       353566
EverCrypt_Sha2_oneshot/sha2_512         1989 ns         1988 ns       353494
OpenSSL_hash_oneshot/sha2_512            858 ns          857 ns       821509
HACL_Sha2_streaming/sha2_224            3782 ns         3781 ns       184416
EverCrypt_Sha2_streaming/sha2_224       3920 ns         3919 ns       178061
OpenSSL_hash_streaming/sha2_224         1665 ns         1665 ns       420022
HACL_Sha2_streaming/sha2_256            3780 ns         3779 ns       185589
EverCrypt_Sha2_streaming/sha2_256       3915 ns         3912 ns       179936
Digestif_sha256                         5690 ns         5684 ns       123481
OpenSSL_hash_streaming/sha2_256         1652 ns         1652 ns       421053
HACL_Sha2_streaming/sha2_384            2644 ns         2643 ns       264792
EverCrypt_Sha2_streaming/sha2_384       2722 ns         2721 ns       257104
OpenSSL_hash_streaming/sha2_384         1918 ns         1918 ns       367579
HACL_Sha2_streaming/sha2_512            2632 ns         2632 ns       265746
EverCrypt_Sha2_streaming/sha2_512       2727 ns         2726 ns       256445
Digestif_sha512                         3892 ns         3891 ns       180184
OpenSSL_hash_streaming/sha2_512         1909 ns         1909 ns       367612```

So there is a huge improvement on ARM M1 for the EverCrypt/Streaming API, bringing it closer to the HACL/SHA2-MB perf.

**Comment by karthikbhargavan** [comment]
On Linux/Intel/GCC-12, the numbers are a bit funny

With the branch `karthik/sha2_benchmark`:
```----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
HACL_Sha2_oneshot/sha2_224              4455 ns         4455 ns       137649
EverCrypt_Sha2_oneshot/sha2_224          724 ns          724 ns       869105
OpenSSL_hash_oneshot/sha2_224           1047 ns         1047 ns       635614
HACL_Sha2_oneshot/sha2_256              4429 ns         4428 ns       137879
EverCrypt_Sha2_oneshot/sha2_256          736 ns          736 ns       874450
OpenSSL_hash_oneshot/sha2_256           1045 ns         1045 ns       617835
HACL_Sha2_oneshot/sha2_384              2756 ns         2756 ns       247297
EverCrypt_Sha2_oneshot/sha2_384         3770 ns         3770 ns       181459
OpenSSL_hash_oneshot/sha2_384           2021 ns         2020 ns       329751
HACL_Sha2_oneshot/sha2_512              2760 ns         2760 ns       248756
EverCrypt_Sha2_oneshot/sha2_512         3760 ns         3760 ns       182737
OpenSSL_hash_oneshot/sha2_512           2000 ns         2000 ns       329015
HACL_Sha2_streaming/sha2_224            5264 ns         5264 ns       115473
EverCrypt_Sha2_streaming/sha2_224       1525 ns         1525 ns       445125
OpenSSL_hash_streaming/sha2_224         1600 ns         1600 ns       420749
HACL_Sha2_streaming/sha2_256            5186 ns         5185 ns       115848
EverCrypt_Sha2_streaming/sha2_256       1492 ns         1492 ns       454361
OpenSSL_hash_streaming/sha2_256         1593 ns         1593 ns       419400
HACL_Sha2_streaming/sha2_384            3749 ns         3748 ns       189023
EverCrypt_Sha2_streaming/sha2_384       4456 ns         4456 ns       133092
OpenSSL_hash_streaming/sha2_384         2992 ns         2992 ns       233930
HACL_Sha2_streaming/sha2_512            3777 ns         3776 ns       187037
EverCrypt_Sha2_streaming/sha2_512       4460 ns         4459 ns       131889
OpenSSL_hash_streaming/sha2_512         3001 ns         3001 ns       227800```

Here, remember that EverCrypt has SHA-NI for x84 machines and this laptop has SHA-NI.
So, the relevant numbers are those for SHA-384 and SHA-512, where EverCrypt/Streaming was 20% slower than HACL/SHA2-MB.

With branch `hacl-star-protz_sha2_thin_wrapper`:

```----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
HACL_Sha2_oneshot/sha2_224              4720 ns         4719 ns       129336
EverCrypt_Sha2_oneshot/sha2_224          969 ns          969 ns       649909
OpenSSL_hash_oneshot/sha2_224           1036 ns         1036 ns       609630
HACL_Sha2_oneshot/sha2_256              4815 ns         4815 ns       130653
EverCrypt_Sha2_oneshot/sha2_256          968 ns          968 ns       666002
OpenSSL_hash_oneshot/sha2_256           1031 ns         1031 ns       638410
HACL_Sha2_oneshot/sha2_384              2984 ns         2984 ns       234429
EverCrypt_Sha2_oneshot/sha2_384         2974 ns         2974 ns       237071
OpenSSL_hash_oneshot/sha2_384           2026 ns         2026 ns       329959
HACL_Sha2_oneshot/sha2_512              2985 ns         2984 ns       230459
EverCrypt_Sha2_oneshot/sha2_512         2967 ns         2967 ns       236603
OpenSSL_hash_oneshot/sha2_512           2004 ns         2004 ns       329330
HACL_Sha2_streaming/sha2_224            5340 ns         5339 ns       119460
EverCrypt_Sha2_streaming/sha2_224       1741 ns         1741 ns       395903
OpenSSL_hash_streaming/sha2_224         1608 ns         1608 ns       417865
HACL_Sha2_streaming/sha2_256            5524 ns         5524 ns       118312
EverCrypt_Sha2_streaming/sha2_256       1706 ns         1706 ns       395558
Digestif_sha256                         4470 ns         4470 ns       159829
OpenSSL_hash_streaming/sha2_256         1599 ns         1599 ns       421693
HACL_Sha2_streaming/sha2_384            3763 ns         3763 ns       188350
EverCrypt_Sha2_streaming/sha2_384       3694 ns         3694 ns       192635
OpenSSL_hash_streaming/sha2_384         3028 ns         3028 ns       232042
HACL_Sha2_streaming/sha2_512            3764 ns         3764 ns       183687
EverCrypt_Sha2_streaming/sha2_512       3708 ns         3708 ns       188160
Digestif_sha512                         3380 ns         3380 ns       205823
OpenSSL_hash_streaming/sha2_512         3079 ns         3079 ns       230350```

Here EverCrypt has caught up with HACL on SHA-384 and SHA-512 but SHA-224 and SHA-256 via HACL is much slower for some reason?

Also: we should get numbers from Clang, if someone has a linux laptop with clang installed (my llvm install is broken)

**Comment by msprotz** [comment]
> but SHA-224 and SHA-256 via HACL is much slower for some reason?

which lines are you specifically referring to? I assume you've applied my patch on the hacl-packages branch?

**Comment by karthikbhargavan** [comment]
With Jonathan's patch, the new numbers, still with GCC-12 on my Linux laptop are:

```----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
HACL_Sha2_oneshot/sha2_224              3716 ns         3716 ns       189530
EverCrypt_Sha2_oneshot/sha2_224          774 ns          774 ns       902342
OpenSSL_hash_oneshot/sha2_224            835 ns          835 ns       836100
HACL_Sha2_oneshot/sha2_256              3720 ns         3720 ns       188035
EverCrypt_Sha2_oneshot/sha2_256          773 ns          773 ns       906019
OpenSSL_hash_oneshot/sha2_256            838 ns          838 ns       832914
HACL_Sha2_oneshot/sha2_384              2387 ns         2387 ns       291488
EverCrypt_Sha2_oneshot/sha2_384         2395 ns         2394 ns       293655
OpenSSL_hash_oneshot/sha2_384           1634 ns         1634 ns       426095
HACL_Sha2_oneshot/sha2_512              2377 ns         2377 ns       291650
EverCrypt_Sha2_oneshot/sha2_512         2379 ns         2379 ns       294732
OpenSSL_hash_oneshot/sha2_512           1637 ns         1637 ns       428697
HACL_Sha2_streaming/sha2_224            4261 ns         4261 ns       164346
EverCrypt_Sha2_streaming/sha2_224       1417 ns         1417 ns       492780
OpenSSL_hash_streaming/sha2_224         1299 ns         1299 ns       539892
HACL_Sha2_streaming/sha2_256            4266 ns         4266 ns       164008
EverCrypt_Sha2_streaming/sha2_256       1417 ns         1417 ns       491703
Digestif_sha256                         3499 ns         3499 ns       199251
OpenSSL_hash_streaming/sha2_256         1308 ns         1308 ns       533317
HACL_Sha2_streaming/sha2_384            3020 ns         3020 ns       231703
EverCrypt_Sha2_streaming/sha2_384       2963 ns         2963 ns       235950
OpenSSL_hash_streaming/sha2_384         2423 ns         2423 ns       289523
HACL_Sha2_streaming/sha2_512            3003 ns         3003 ns       233167
EverCrypt_Sha2_streaming/sha2_512       2944 ns         2944 ns       236454
Digestif_sha512                         2640 ns         2640 ns       264692
OpenSSL_hash_streaming/sha2_512         2419 ns         2419 ns       288369
```

**Comment by msprotz** [comment]
I am delighted to see we're faster than OpenSSL!

**Comment by karthikbhargavan** [comment]
Vale SHA-NI-based SHA-256 is seemingly faster than OpenSSL.

**Review by R1kM — APPROVED** [review]
This looks good to me, apart from the naming issue raised by Karthik that will be addressed in #789.
@msprotz , could you also add an entry in CHANGES.md for the bundling of the C code? Thanks!

**Comment by msprotz** [comment]
Changes are done. Pinging @franziskuskiefer since you'll need to apply the patch listed in the issue description above to hacl-packages.

**Comment by karthik-cryspen** [comment]
I can make those changes, but does it make sense to do them before merging this?

**Comment by msprotz** [comment]
Not sure which changes you're referring to. I'm in favor of merging this asap.

**Comment by karthikbhargavan** [comment]
I meant I can do the patch/changes in hacl-packages.

**Comment by msprotz** [comment]
Ah yes, certainly let's merge this first before patching hacl-packages. Just wanted to give everyone a heads-up so that Franziskus or you don't end up doing extra work since the patch is already there.

**Comment by msprotz** [comment]
@karthik-cryspen is there anything else you need here before approving this PR?

**Review by karthikbhargavan — APPROVED** [review]

**Comment by msprotz** [comment]
@pnmadelaine could use your help here figuring out why CI hasn't kicked in (in spite of my commit "kick CI"!)

thanks!

**Comment by msprotz** [comment]
Ok so the solution for CI was to push to a different branch, which in turn triggered Hydra, which led to a successful reporting of the same commit as being green.

**Pull request merged**
