### PR TITLE
Use new option from fstarlang/karamel#299 and help with #644

### PR DESCRIPTION
**Pull request by msprotz**
See #644. Basically, the addition of functions that perform allocations in static headers mean that these function bodies may now be parsed by a C++ compiler, which mandates that allocations be cast to their destination type (C89 also forbids this, but C99 adds implicit casts.)

We now cast every allocation. Simple. I'll push a commit that performs a refresh for dist/gcc-compatible just so that we can see the impact.

### CODE REVIEW

**Comment by msprotz** [comment]
@franziskuskiefer can you confirm this fixes your build issue? thanks!

**Review by polubelova — APPROVED** [review]
Thanks!

**Review by R1kM — APPROVED** [review]
Looks good to me, thanks!

**Comment by franziskuskiefer** [comment]
> @franziskuskiefer can you confirm this fixes your build issue? thanks!

Yes, this fixes the issue. (CI: https://github.com/cryspen/hacl-packages/pull/232/checks)

**Pull request merged**
