### PR TITLE
Vale.Transformers.InstructionReorderSanityChecks: use --admit_smt_que…

### PR DESCRIPTION
**Pull request by mtzguido**
…ries instead of --lax

We are planning to make --lax only settable when invoking F*, and not within a file. See https://github.com/FStarLang/FStar/pull/3337.

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to HACL*?
_Put an `x` in the boxes that apply_

- [x] Proof maintenance (non-breaking change which fixes a proof regression)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New algorithm or feature (non-breaking change which adds functionality)
- [ ] Improved performance (fix or feature that would improve performance of some algorithm on some platform)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CODE_OF_CONDUCT.md](https://github.com/hacl-star/hacl-star/blob/main/CODE_OF_CONDUCT.md) doc
- [x] I have read and agree to submit my changes under the [LICENSE](https://github.com/hacl-star/hacl-star/blob/main/LICENSE)
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have edited [CHANGES.md](https://github.com/hacl-star/hacl-star/blob/main/CHANGES.md) (if appropriate)

### CODE REVIEW

**Review by msprotz — APPROVED** [review]
Out of curiosity, have you checked whether the smt encoding bug mentioned in the comment still exists, and if so, what is the corresponding issue?

**Comment by mtzguido** [comment]
It did trigger again! But I didn't look up the issue. If it's not there I can add (in a week or so, leaving on vacation).

**Comment by msprotz** [comment]
Let's at least try to track down the smt encoding issue once you're back, I'm having a hard time imagining that the bug is still there -- if it is, sounds like it'd definitely be worth fixing

**Comment by mtzguido** [comment]
Here's the report from Jay, it's still there https://github.com/FStarLang/FStar/issues/1796. I think it is related to friending, since I can't minimize that bit away.

**Pull request merged**
