### PR TITLE
Miscellaneous proof taming

### PR DESCRIPTION
**Pull request by mtzguido**
## Proposed changes

Hi. I'm working on switching the default Z3 version to the latest master and making sure our projects still verify. This is part of the tweaks I had to do to HACL* to get it to work with the newest Z3.

I have some more locally, but some of them are slightly suspect and I would like to confirm they are not Z3 regressions. The ones here however seems like all around improvements, and still verify with Z3 4.8.5.

## Types of changes

What types of changes does your code introduce to HACL*?
_Put an `x` in the boxes that apply_

- [x] Proof maintenance (non-breaking change which fixes a proof regression)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New algorithm or feature (non-breaking change which adds functionality)
- [ ] Improved performance (fix or feature that would improve performance of some algorithm on some platform)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CODE_OF_CONDUCT.md](https://github.com/hacl-star/hacl-star/blob/main/CODE_OF_CONDUCT.md) doc
- [x] I have read and agree to submit my changes under the [LICENSE](https://github.com/hacl-star/hacl-star/blob/main/LICENSE)
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have edited [CHANGES.md](https://github.com/hacl-star/hacl-star/blob/main/CHANGES.md) (if appropriate)

### CODE REVIEW

**Review by msprotz — COMMENTED** [review]
Thanks Guido. Are these regressions caused by changes in upstream F*? I'm wondering what caused these proofs to regress.

Do we have any understanding of what's happening? I know these things are complicated, but it would be good if we could get some advice from the F* team as to how proofs should be authored in a way that makes them more robust and future-proof.

**Comment by mtzguido** [comment]
Hi Jonathan. I think it's just that the new Z3's heuristics are slightly different, and then proofs that are "close to edge" can just fail, and need some tweaking. (The F* I'm using for the SMT upgrade is exactly the current master, just flipping the default Z3 version.) Most of this PR is just rlimit tweaks and some sanity assertions.

Some good practices I try to follow when stabilizing are:
- Never use `#set-options`/`#reset-options`, use `#push-options`/`#pop-options` instead. Unless it's something that must apply to the whole file, if so `#set-options` is OK. This is just to make it easier to follow the current rlimit/fuel/smtopt settings.
- Keep `--hint_info` on to see what's happening with the queries.
- If a definition is generating hundreds of queries, the auto split may have kicked in to report a better error location. I find it's usually better to keep `--split_queries no` or `--split_queries always`. (Some related info [here](https://github.com/FStarLang/FStar/pull/2776#issuecomment-1502397472))
- Use `--quake 1/10/k` while proof taming to get an estimate of stability, it will try every query 10 times and report the success rate, accepting it if at least one succeeded.
- Using that and the "sliding admit style", it's usually easy to find the hard assertions in a proof. For those, attempt `assert_spinoff` to try to prove them in a separate query, and `assert_norm`.
- If one particular assertion requires more rlimit/fuels, set them for that assertion only using a tactic, like this (from this PR):
```fstar
        assert (state_eq_S true s1_orig s2_orig /\ state_eq_S true s1 s2)
            by (let open FStar.Tactics in
                set_rlimit 100;
                ());
```
The "global" rlimit should ideally remain small.
- If all else fails, using `--retry 5` can help advance.

Not really deep insights... but it's most of the procedure I use to make stuff more robust.

I'm thinking of adding a quake variant that will create a logfile with some robustness info, which we can then pick up and summarize for each project (similar to the resource monitoring stuff). Maybe we can have a nightly/weekly job that tries everything 20 times and reports the least stable proofs.

**Comment by mtzguido** [comment]
> I'm a bit worried about the additions of `--retry 5`, it seems like unstable proofs would fly under the radar more easily.

Yes, totally reasonable. If you prefer, we can drop that commit from this PR and wait for the next set of changes for the new Z3.

**Comment by mtzguido** [comment]
To be superseded soon :-)

**Pull request closed without merging**
