### PR TITLE
Misc rlimit increases

### PR DESCRIPTION
**Pull request by mtzguido**
There was an F* change which can impact the order of queries. This apparently broke a few brittle proofs. Updating some rlimits here. I don't think hints are needed.

## Types of changes

What types of changes does your code introduce to HACL*?
_Put an `x` in the boxes that apply_

- [x] Proof maintenance (non-breaking change which fixes a proof regression)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New algorithm or feature (non-breaking change which adds functionality)
- [ ] Improved performance (fix or feature that would improve performance of some algorithm on some platform)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CODE_OF_CONDUCT.md](https://github.com/hacl-star/hacl-star/blob/main/CODE_OF_CONDUCT.md) doc
- [x] I have read and agree to submit my changes under the [LICENSE](https://github.com/hacl-star/hacl-star/blob/main/LICENSE)
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have edited [CHANGES.md](https://github.com/hacl-star/hacl-star/blob/main/CHANGES.md) (if appropriate)

### CODE REVIEW

**Review by msprotz — APPROVED** [review]

**Comment by R1kM** [comment]
Seems there was an error in Hacl.Bignum.Lib. Possibly related? Otherwise, feel free to merge.

**Review by R1kM — APPROVED** [review]

**Comment by pnmadelaine** [comment]
@R1kM the error is also on main, see https://github.com/hacl-star/hacl-star/actions/runs/7154516932/job/19482133528 and https://github.com/hacl-star/hacl-nix/actions/runs/7161644729/job/19497530859

**Comment by mtzguido** [comment]
Probably I missed increasing some rliimt, sorry, will try again and update.

(Random comment: recently I added [this script](https://github.com/FStarLang/steel/blob/main/.scripts/fstar_errs.sh) to Steel CI grab all the F* errors and report them separately. I'll probably add it to the F* repo too. May be useful for you folks, both in CI and locally.)

**Comment by mtzguido** [comment]
Updated, sorry for the delay, was on a slow machine today :).

I think this should pass without new hints, but if it doesn't could I just add those?

**Comment by mtzguido** [comment]
Updated, not yet working.

Having a hard time with this. I'm down to just Vale failures, which don't seem to be a question of rlimit, but I'm pretty sure I got a green recently. List: [http://sprunge.us/15HTEE](http://sprunge.us/15HTEE)

I didn't add hints to the PR but they can be found here: https://github.com/mtzguido/hacl-star/tree/rlimits%2Bhints

I'll look at F*, maybe something broke this, but does it ring a bell to anyone?

**Comment by mtzguido** [comment]
Nevermind.. it's an F* regression :). Looking into it. I'll ping here when fixed so CI can be run on the updated F*.

**Comment by mtzguido** [comment]
F* fixed, and I got a green locally. Should be good now, apologies for the spam. I pushed an empty commit so CI and automerge kick in.

**Comment by msprotz** [comment]
Thanks Guido!

**Pull request merged**
