### PR TITLE
Add missing #include <sys/syscall.h> in Lib_RandomBuffer_System.c

### PR DESCRIPTION
**Pull request by vincent-botbol**
## Proposed changes

This PR adds an include that introduces the `SYS_getrandom` cpp flag used to call the `getrandom` syscall.

For instance, without the `#include <sys/syscall.h>`, the following program yields `ko` :
```
#include <fcntl.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>

int main(){
#ifdef SYS_getrandom
  printf("ok\n");
#else
  printf("ko\n");
#endif
  return 0; }
```

## Types of changes

What types of changes does your code introduce to HACL*?
_Put an `x` in the boxes that apply_

- [ ] Proof maintenance (non-breaking change which fixes a proof regression)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New algorithm or feature (non-breaking change which adds functionality)
- [ ] Improved performance (fix or feature that would improve performance of some algorithm on some platform)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CODE_OF_CONDUCT.md](https://github.com/hacl-star/hacl-star/blob/main/CODE_OF_CONDUCT.md) doc
- [ ] I have read and agree to submit my changes under the [LICENSE](https://github.com/hacl-star/hacl-star/blob/main/LICENSE)
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have edited [CHANGES.md](https://github.com/hacl-star/hacl-star/blob/main/CHANGES.md) (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by msprotz** [comment]
FYI libsodium does something much more fancy, but then it requires a configure script and a lot of platform feature detection, but maybe Tezos doesn't need that since you target fewer platforms?

**Comment by victor-dumitrescu** [comment]
Tezos does use this module directly, which is how @vincent-botbol found out that (at least on some systems) `SYS_getrandom` is not defined in `unistd.h`

**Comment by msprotz** [comment]
Old libcs won't have this. But if it works for Tezos, I'm fine with merging it.

**Comment by vincent-botbol** [comment]
Apologies for the delayed answer. We do require recent libc through our dependencies so I don't think it will be an issue for Tezos.

**Comment by msprotz** [comment]
Ok thanks. Are others in favor? @R1kM @polubelova?

**Review by polubelova — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
