### PR TITLE
Upstream miscellaneous cleanups

### PR DESCRIPTION
**Pull request by franziskuskiefer**
This PR upstreams Cryspen changes that
 - remove some gratuitous VLAs that were showing up because of bad normalizations
 - simplify WASM build following fstarlang/kremlin@d7750574d07db9222d552b18d0c189794dd68c23
 - enforce that 128/256 blake2 functions are in their own respective files
 - restore abstract struct for hashes
 - codegen optimization in merkletree example

**Note:** this PR requires #619 to be merged first

### CODE REVIEW

**Comment by msprotz** [comment]
So much for separating things into different PRs. This one needs a fix from #621 that adds libintvector.h to the test files... let's wait until #621 is merged then I'll update this one.

**Review by R1kM — APPROVED** [review]
Several of the changes (especially related to Blake2) seem to also be in #619, the rest looks good to me.

**Comment by msprotz** [comment]
@franziskuskiefer let us know if there's anything in here that hasn't been merged in upstream already

**Comment by msprotz** [comment]
@pnmadelaine is there any way to tell which task was running when this job timed out?

**Comment by franziskuskiefer** [comment]
> @franziskuskiefer let us know if there's anything in here that hasn't been merged in upstream already

I think it's all in.

**Comment by franziskuskiefer** [comment]
@sonmarcho please close this when you had a look at it and there's nothing to change.

**Comment by msprotz** [comment]
@franziskuskiefer do you mind merging hacl-star/hacl-star@main into this branch? just to see how much of a diff there actually is, before Son can review

**Comment by franziskuskiefer** [comment]
I merged main in here and there's no diff left.

**Pull request closed without merging**
