### PR TITLE
hints for F* PR #3515

### PR DESCRIPTION
**Pull request by nikswamy**
## Proposed changes

F* PR https://github.com/FStarLang/FStar/pull/3515 changes the symbol generator, resulting in the names of top-level anonymous definitions changing. E.g., what was previously `let _17 = ...` could now be `let _0 = ...`. This means that hint files which previously references top-level anonymous definitions are invalidated and I had a failure in one proof as a result: Hacl.Impl.Curve25519.Field64.Vale.fst.

This PR updates all the hints and for use with the current F* master. 

## Types of changes

What types of changes does your code introduce to HACL*?
_Put an `x` in the boxes that apply_

- [x] Proof maintenance (non-breaking change which fixes a proof regression)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New algorithm or feature (non-breaking change which adds functionality)
- [ ] Improved performance (fix or feature that would improve performance of some algorithm on some platform)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CODE_OF_CONDUCT.md](https://github.com/hacl-star/hacl-star/blob/main/CODE_OF_CONDUCT.md) doc
- [x] I have read and agree to submit my changes under the [LICENSE](https://github.com/hacl-star/hacl-star/blob/main/LICENSE)
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have edited [CHANGES.md](https://github.com/hacl-star/hacl-star/blob/main/CHANGES.md) (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by nikswamy** [comment]
@R1kM @protz Any chance you could take a look at this? I think hacl-star is currently broken with F* master, due to a failure in the file I mentioned above: Hacl.Impl.Curve25519.Field64.Vale.fst.

**Review by msprotz — APPROVED** [review]
Fine by me, but just to make sure, the issue is fixed with a mere hint refresh?

**Comment by nikswamy** [comment]
Yes, it seems to have been solved by a hint refresh. This is expected, since a bunch of the hints that mention top-level anonymous definitions were invalidated

**Comment by msprotz** [comment]
Great, thank you

**Pull request merged**
