### PR TITLE
ci: update and fix `hintsanddist.yml`

### PR DESCRIPTION
**Pull request by pnmadelaine**
The new regeneration workflow is broken: it commits the flake lock file and a link to the store.
I did not realize that https://github.com/peter-evans/create-pull-request is designed to commit any uncommitted changes before creating a PR.
The old regeneration workflow did not write anything on disk beside the intended changes, so I never noticed.
This should fix the issue by not writing the lock file and cleaning the repository before running `create-pull-request`.

### CODE REVIEW

**Comment by msprotz** [comment]
Other reviewers: @pnmadelaine informed me on slack that this still needs a small tweak before we can merge it (other than that, looks good).

Question: won't the call to `git restore` also revert the hints that we intend to be part of the commit?

**Comment by pnmadelaine** [comment]
@msprotz don't you confuse it with `git reset`? `git restore .` is going to restore modified files to the state of `HEAD`, which is the commit we create in the previous step.

**Review by msprotz — APPROVED** [review]

**Comment by msprotz** [comment]
@R1kM ? review?

**Review by R1kM — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
