### PR TITLE
Nix: simplify source filter for Rust extraction

### PR DESCRIPTION
**Pull request by pnmadelaine**

### CODE REVIEW

**Comment by msprotz** [comment]
```
hacl-star> errorerror::  failed to load manifest for workspace member `/build/source/dist/rs/krml`failed to load manifest for workspace member `/build/source/dist/rs/krml`
hacl-star> Caused by:
hacl-star>   failed to read `/build/source/dist/rs/krml/Cargo.toml`
hacl-star> Caused by:
hacl-star> Caused by:
hacl-star>   No such file or directory (os error 2)
hacl-star>   failed to read `/build/source/dist/rs/krml/Cargo.toml`
hacl-star> Caused by:
hacl-star>   No such file or directory (os error 2)
hacl-star> make[1]: *** [Makefile:129: test-rust] Error 101
hacl-star> make[1]: *** Waiting for unfinished jobs....
hacl-star> make[1]: *** [Makefile:969: compile-rust] Error 101
```

**Comment by msprotz** [comment]
`dist/rs/krml` is handwritten, is it in the right place in your PR?

**Comment by msprotz** [comment]
As a general remark, I don't see any comments in this file, so I think you should at the very least explain what these two file lists do (unless you want to be on the hook for maintaining this file until your last breath, which is fine by me!)

**Comment by pnmadelaine** [comment]
> (unless you want to be on the hook for maintaining this file until your last breath, which is fine by me!)

part of the ship, part of the crew

**Comment by pnmadelaine** [comment]
> `dist/rs/krml` is handwritten, is it in the right place in your PR?

yes!

**Review by msprotz — APPROVED** [review]
Perfect, great! Thanks for this big improvement.

**Comment by msprotz** [comment]
hacl-star> cc1: fatal error: dist/test/c/Hacl_Test_HMAC_DRBG.c: No such file or directory

try updating your branch?

**Review by R1kM — APPROVED** [review]

**Pull request merged**
