### PR TITLE
Runtime check in all streaming APIs that the maximum length has not been exceeded

### PR DESCRIPTION
**Pull request by msprotz**
Before we distribute the streaming APIs more widely, I'd like to fix this.

@R1kM @sonmarcho: `update_small` fails to verify on my machine. I did some z3 profiling, and this is what I get:

```
[quantifier_instances] lemma_LowStar.Monotonic.Buffer.modifies_liveness_insensitive_region_buffer_weak :  13898 :   8 : 7
[quantifier_instances] FStar.Seq.Base_pretyping_7efa52b424e80c83ad68a652aa3561e4 :  17323 :   8 : 9
[quantifier_instances] lemma_LowStar.Monotonic.Buffer.modifies_buffer_elim :  20563 :   9 : 9
[quantifier_instances] equation_FStar.Monotonic.Heap.equal_dom :  21881 :   9 : 10
[quantifier_instances] typing_FStar.Monotonic.Heap.equal_dom :  21881 :   9 : 10
[quantifier_instances] lemma_FStar.HyperStack.ST.lemma_same_refs_in_all_regions_elim :  21887 :   8 : 9
[quantifier_instances] Prims_pretyping_f537159ed795b314b4e58c260361ae86 :  24098 :  14 : 15
[quantifier_instances] bool_inversion :  24098 :  14 : 15
[quantifier_instances] unit_inversion :  26555 :   4 : 5
[quantifier_instances] Prims_pretyping_f8666440faa91836cc5a13998af863fc :  26556 :   4 : 5
[quantifier_instances] lemma_LowStar.Monotonic.Buffer.loc_disjoint_union_r_ :  35914 :  11 : 12
[quantifier_instances] refinement_interpretation_Tm_refine_ac201cf927190d39c033967b63cb957b :  38585 :  19 : 20
[quantifier_instances] primitive_Prims.op_Subtraction :  52733 :  18 : 19
[quantifier_instances] primitive_Prims.op_Addition :  56457 :  18 : 19
[quantifier_instances] refinement_interpretation_Tm_refine_35a0739c434508f48d0bb1d5cd5df9e8 :  68413 :  19 : 20
[quantifier_instances] refinement_interpretation_Tm_refine_d83f8da8ef6c1cb9f71d1465c1bb1c55 :  71011 :  18 : 19
[quantifier_instances] int_typing :  78155 :  20 : 21
[quantifier_instances] int_inversion :  82765 :  20 : 21
[quantifier_instances] lemma_FStar.Seq.Base.lemma_index_app1 :  91269 :  13 : 14
[quantifier_instances] lemma_FStar.Seq.Base.lemma_index_app2 :  91308 :  13 : 14
[quantifier_instances] Prims_pretyping_ae567c2fb75be05905677af440075565 :  93086 :  20 : 21
[quantifier_instances] refinement_interpretation_Tm_refine_542f9d4f129664613f2483a6c88bc7c2 :  94505 :  19 : 20
[quantifier_instances] projection_inverse_BoxInt_proj_0 : 120318 :  20 : 21
[quantifier_instances] lemma_LowStar.Monotonic.Buffer.loc_disjoint_sym_ : 120895 :  14 : 15
[quantifier_instances] constructor_distinct_BoxInt : 135585 :  20 : 21
[quantifier_instances] lemma_FStar.Seq.Base.lemma_index_slice : 153246 :  13 : 14
[quantifier_instances] lemma_LowStar.Monotonic.Buffer.loc_disjoint_includes_r : 226015 :  14 : 15
[quantifier_instances] typing_LowStar.Monotonic.Buffer.loc_disjoint : 313740 :  14 : 15
```

I don't know why loc_disjoint_includes_r triggers so much. Is it a runaway pattern? Maybe @tahina-pro has an opinion on what's happening.

In any case, if any of you has a chance to fix that proof, then that'd be of great help. Thanks.

### CODE REVIEW

**Review by polubelova — APPROVED** [review]
Thanks! 

It would be nice to address two small comments:
- add a comment to `Hacl_Streaming_*.h` saying that `0` stands for `Success` and `1` for `Failure`.
- update `tests/*-streaming` to handle a return value

**Comment by msprotz** [comment]
I made some progress on the proof, so I hope it works. Marina, I've addressed your comments, thanks.

**Comment by msprotz** [comment]
Ugh so my proof doesn't work on the build machine, and Hacl.Spec.PrecompBaseTable.fst also breaks too?!

**Comment by polubelova** [comment]
Thanks Jonathan. We can first merge #666 into `main` and then see if we need to tweak some proofs for this PR.

**Review by R1kM — APPROVED** [review]

**Pull request merged**
